{% set name = "era5cli" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/era5cli-{{ version }}.tar.gz
  sha256: 60fbe777ccc565c553b67fb0c4157b8c6685e024fdf1dc65504a465ffde50fff

build:
  entry_points:
    - era5cli = era5cli.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling >=1.8.0
    - hatch-vcs
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >=3.7
    - cdsapi ==0.5.1
    - pathos
    - ptable
    - netcdf4

test:
  imports:
    - era5cli
  commands:
    - pip check
    - era5cli --help
  requires:
    - pip

about:
  home: https://github.com/ewatercycle/era5cli
  summary: A command line interface to download ERA5 data from the Copernicus Climate Data Store. https://climate.copernicus.eu/..
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zklaus
    - BSchilperoort
